=== tong-ho/JsonSchemaDemo/JsonSchemaDemo/test.schema.json
{
  "$schema": "http://json-schema.org/schema",
  "$id": "https://illumina.com/schema.json",
  "title": "Test Schema",
  "description": "Description for my test schema",
  "type": "object",
  "properties": {
    "stringProperty": {
      "description": "description of a string property",
      "type": "string"
    },
    "requiredStringProperty": {
      "description": "description of a required string property",
      "type": "string"
    },
    "numberProperty": {
      "description": "description of a number property",
      "type": "number"
    },
    "numberBetween1and5Property": {
      "description": "description of a numberBetween1and5Property property",
      "type": "number",
      "exclusiveMinimum": 1,
      "exclusiveMaximum": 5
    },
    "complexProperty": {
      "description": "description of complex property",
      "type": "object",
      "properties": {
        "length": {
          "type": "number"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [ "length", "name" ]
    },
    "simpleArray": {
      "description": "description of an array property",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "complexArray": {
      "description": "complex array description",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "length": {
            "type": "number"
          },
          "name": {
            "type": "string"
          }
        }
      }
    },
    "enumProperty": {
      "description": "description of an enum",
      "type": "string",
      "enum": ["North", "West", "South", "East"]
    },
    "timestampRegex": {
      "description": "timestamp regex description",
      "type": "string",
      "pattern": "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])[T\\s]+(0[0-9]|1[0-9]|2[0-4]):[0-5][0-9]:[0-5][0-9]([\\,\\.]\\d{3})?$",
      "examples": ["2021-01-01 21:01:01"]
    }
  },
  "required": [ "requiredStringProperty" ]
}

=== tong-ho/JsonSchemaDemo/JsonSchemaDemo/test.json
{
  "$schema": "test.schema.json",
  "stringProperty": "test",
  "numberProperty": 0,
  "numberBetween1and5Property": 4,
  "complexProperty": {
    "length": 0,
    "name": "test"
  },
  "simpleArray": [ "test" ],
  "complexArray": [
    {
      "length": 0,
      "name": "test"
    }
  ],
  "enumProperty": "North",
  "requiredStringProperty": "test",
  "timestampRegex":"2021-01-01 21:01:01"
}
